server:
  address: localhost
  port: 8080
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: D:/gits/springbootDemo/demo/src/main/resources/licensingservice/default/
  datasource:
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    password: 131400
    url: jdbc:mysql://127.0.0.1:3306/phonestore
  thymeleaf:
    check-template-location: true
    suffix: .html
    encoding: UTF-8
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    database: 0
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-wait: -1
        max-active: 8
mybatis:
  type-aliases-package: com.example.demo.pojo
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
  