server:
  address: localhost
  port: 8080
spring:
  datasource:
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    password: 131400
    url: jdbc:mysql://127.0.0.1:3306/phonestore
  thymeleaf:
    check-template-location: true
    suffix: .html
    encoding: UTF-8
mybatis:
  type-aliases-package: com.example.demo.pojo
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml